#! /bin/tcsh

set DIR = /home/projects/mniel/ClassII/data_BjoernPeters_20092007

foreach a ( DRB1_0101 DRB1_0301 DRB1_0401 DRB1_0404 DRB1_0405 DRB1_0701 DRB1_0802 DRB1_0901 DRB1_1101 DRB1_1302 DRB1_1501 DRB3_0101 DRB4_0101 DRB5_0101 IAb IAd IAs IEd )

mkdir -p $a

cd $a

foreach n ( 0 1 2 3 4 )

cat $DIR/$a/data/c00$n | gawk '{if ( $2<0 ) { o=0 } else {o=$2} print $1,o}' > c00$n

end

cat c00? > all

cd ..

end
